version: '3.3'
services:
  db:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: balkanid
    volumes:
      - "/Users/suraj/github-classroom/BalkanID-University/balkanid-summer-internship-vit-vellore-2023-suraj-ranganath/dbVol:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    expose:
       - "5432"

  redis:
    image: "redis:alpine"

  balkanidsummerinternshipvitvellore2023surajranganath:
    image: balkanidsummerinternshipvitvellore2023surajranganath
    container_name: python-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: balkanid
      POSTGRES_HOST: postgres-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    # ports:
    #   - "5432:5432"
    volumes:
      - "/Users/suraj/github-classroom/BalkanID-University/balkanid-summer-internship-vit-vellore-2023-suraj-ranganath/dbVol:/var/lib/postgresql/data:rw"




